# Generated by Django 5.2.7 on 2026-02-26 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='experience',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
