# Generated by Django 5.2.7 on 2026-03-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_candidateprofile_address_candidateprofile_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='education',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
