# Generated by Django 5.2.7 on 2026-03-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_alter_candidateprofile_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='experience',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
