# Generated by Django 5.2.7 on 2026-03-29 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_application_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='recruiter',
            new_name='posted_by',
        ),
    ]
