# Generated by Django 5.2.7 on 2026-03-29 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='scheduled', max_length=20),
        ),
    ]
