# Generated by Django 5.2.7 on 2026-03-29 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0003_alter_interview_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='interview',
            unique_together=set(),
        ),
    ]
