# Generated by Django 5.2.7 on 2026-03-29 20:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0004_alter_interview_unique_together'),
        ('jobs', '0003_application_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='interview',
            unique_together={('job', 'candidate')},
        ),
    ]
